# Dark Theme Colors
primary_color: "#2D3748"
secondary_color: "#4A5568"
accent_color: "#63B3ED"
text_color: "#E2E8F0"
background_color: "#1A202C"
success_color: "#48BB78"
warning_color: "#ED8936"
error_color: "#F56565"
